### PR TITLE
feat: support all wasm-pack options

### LINKED ISSUE #5: Custom wasm-pack build command
I want to use the following wasm-pack for building my rust program:
```json
"wasm": "wasm-pack build --target bundler",
```
or 
`--target nodejs`

Is this possible using rollup-plugin-rust?

In the [wasm-pack plugin](https://github.com/wasm-tool/wasm-pack-plugin), I can do this using extraArgs:
```js
extraArgs: "--target bundler --mode normal",
```

### PR DESCRIPTION
**Pull request by aminya**
Adds all the supported `wasm-pack` options: https://rustwasm.github.io/wasm-pack/book/commands/build.html

Fixes #5

### CODE REVIEW

**Comment by aminya** [comment]
@Pauan Could you check this out?

**Comment by Pauan** [comment]
@aminya I don't contribute to Rust anymore. As for this PR:

* `outName` is unnecessary (it's an implementation detail which never needs to be changed by the user).

* `target` is useless, since the target must always be `web`.

* `scope` does not make sense, since it's not creating an npm package.

* `mode` is potentially useful, but I don't want to leak implementation details unless needed. What is your use case for `mode`?

**Comment by aminya** [comment]
It is not up to you and me to decide which options are useful or useless. The original wasm-pack repository has disregarded this plugin in their example because these options are missing or not working. [See the docs that say the only working plugin is webpack](https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html#bundlers). 

The webpack plugin has it all:
https://github.com/wasm-tool/wasm-pack-plugin

**Comment by aminya** [comment]
Regarding my use case: 

> @aminya I don't contribute to Rust anymore. As for this PR:
> 
> * `outName` is unnecessary (it's an implementation detail which never needs to be changed by the user).

I need this because I use multiple Rust projects

> * `target` is useless, since the target must always be `web`.

I need this because I want to use `nodejs` or `bundler`. My wasm runs in Node

> * `scope` does not make sense, since it's not creating an npm package.

I need this for testing the wasm.

**Comment by Pauan** [comment]
@aminya You seem to be misunderstanding how this plugin works.

If you want multiple Rust projects, just import multiple `Cargo.toml` files:

```js
import rust from "@wasm-tool/rollup-plugin-rust";

export default {
    input: {
        foo: "foo/Cargo.toml",
        bar: "bar/Cargo.toml",
        qux: "qux/Cargo.toml"
    },
    plugins: [
        rust(),
    ],
};
```

You cannot use `nodejs` or `bundler` mode. By default Rollup will work in the browser. If you want to use it in Node you can instead [change the Rollup `format`](https://rollupjs.org/guide/en/#outputformat), like this:

```js
import rust from "@wasm-tool/rollup-plugin-rust";

export default {
    input: {
        foo: "Cargo.toml"
    },
    output: {
        format: "cjs"
    },
    plugins: [
        rust(),
    ],
};
```

> I need this for testing the wasm.

I don't understand how that's related to `scope`. You test the wasm by running it, scope has nothing to do with that.

**Comment by Pauan** [comment]
> It is not up to you and me to decide which options are useful or useless.

I was a Rust Wasm Core member, and I have heavily contributed to wasm-pack, wasm-bindgen, and all of the plugins. I am *well* aware of which options are useless or useful for this plugin.

The Webpack plugin works completely differently from this plugin, they are not the same.

The wasm-pack docs are simply outdated, that's all.

**Comment by aminya** [comment]
> You cannot use `nodejs` or `bundler` mode. By default Rollup will work in the browser. If you want to use it in Node you can instead [change the Rollup `format`](https://rollupjs.org/guide/en/#outputformat), like this:
> 
> ```js
> import rust from "@wasm-tool/rollup-plugin-rust";
> 
> export default {
>     input: {
>         foo: "Cargo.toml"
>     },
>     output: {
>         format: "cjs"
>     },
>     plugins: [
>         rust(),
>     ],
> };
> ```

Have you tested this in Node? It does not work. We always use `cjs` output in the rollup plugin of our organization. I am trying to integrate rust into this plugin, but it does not work. We cannot switch to webpack just because of this.
https://github.com/atom-ide-community/rollup-plugin-atomic

Webpack plugin in bundler mode or nodejs mode creates the `wasm-pack` folder. Then I can import the wasm. I could get similar result by using this pull request and #7. But the import options still need work.

**Comment by Pauan** [comment]
Since the underlying issue with Node has been fixed (and these options are not useful for this plugin), I'm going to close this.

**Pull request closed without merging**
